### PR TITLE
Parking spot

### PR DESCRIPTION
**Pull request by farhanali3193**
@ahamilton454 @carrjsn @sharplessHQ @matthewwrobel @raphaelwho
1. Created the manage spot preview/ booking spot preview.
2. Can't really understand how big this component should be. Would like to know what you guys think.
3. The address has been broken down into 2 lines. Let me know if this doesn't work.
3. Added 2 react svg components in the shared folder: Chevron Right and Trash.

### CODE REVIEW

**Comment by farhanali3193** [comment]
@ahamilton454 @carrjsn @sharplessHQ @matthewwrobel @raphaelwho 
1. Added a map component using @react-google-maps-api. Also added react-geocode to convert addresses into lat and long.
2. Added dotenv-webpack to use env vars in react components.
3. Please run npm install. 
4. Also create a google map api key and add it to your .env file. The key should be named "GOOGLE_API".

**Comment by farhanali3193** [comment]
@matthewwrobel 
1. Added PostGIS and created a spatial db and entered a couple of records as shown
2.  in schema.sql.
2. Able to render map from the locations queried from the db. 
3. Search nearby query works as well.
4. When a user adds a new spot, we just need to add it in the table using the insert statement in schema.sql on line 36. The user's address can be converted into lat and long using a lib called react-geocode.
5. There is a conflict in the dependencies used. I have been using @react-google-maps-api as the Google Maps Wrapper while I noticed you used a different library. They look pretty similar to me, so let me know which one you'd like to use.

**Comment by matthewwrobel** [comment]
@farhanali3193 Let use @react-google-maps-api, the other one (that I used) isn't supported any more. I'll check the rest out duing class tonight

**Comment by matthewwrobel** [comment]
Also, as far as adding spots, theres a feature to implement that uses the google map api to autocomplete addresses. have you explored that? I'm thinking we may be able to extract lat/lng data from that, too, so we might not even need react-geocode. I could be wrong about that, though.

**Comment by farhanali3193** [comment]
@matthewwrobel Correct me if I'm wrong, but I believe you're talking about the auto-complete feature when the host or the renter is typing the address. I haven't thought about this feature at all. However, there's a library called "react-places-autocomplete". I didn't use it because I thought we didn't need the auto-complete feature. We can check it out tonight, if you want.

**Comment by matthewwrobel** [comment]
@farhanali3193 Yes, that's exactly what I'm talking about. You're right--not part of BMR so maybe not worth putting time into. But it seems pretty easy to set up and would make the app way more user-friendly. Maybe we implement that later.

**Review by matthewwrobel — APPROVED** [review]
Looks great!

**Pull request merged**
